name: build-petr4

on:
  # Trigger the workflow on push or pull request,
  # but only for the main branch
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-ubuntu:
    runs-on: ubuntu-latest

    steps: 
      - name: checkout/main
        uses: actions/checkout@main
      
      - name: setup-ocaml
        uses: ocaml/setup-ocaml@v1
        with:
          ocaml-version: '4.12.0'

      - name: build-ubuntu
        run: ./.github/scripts/build-petr4-ubuntu.sh
        shell: bash

  build-macos-latest:
    runs-on: macos-latest

    steps: 
      - name: checkout-main
        uses: actions/checkout@main
        
      - name: setup-ocaml
        uses: ocaml/setup-ocaml@v1
        with: 
          ocaml-version: '4.12.0'
        
      - name: build-macos
        run: ./.github/scripts/build-petr4-macos.sh
        shell: bash


    
     
