name: ci-stf-test

on:
  workflow_dispatch:
  # workflow_run:
  #   workflows: ["push-petr4-docker-img"]
  #   branches: [main]
  #   types:
  #     - completed

jobs:
  petr4-vs-p4c:
    runs-on: ubuntu-latest
    # if: ${{ github.event.workflow_run.conclusion == 'success' }}
    # container:
      # image: pataei/petr4:main
    steps: 
      - name: update git version
        run: |
          sudo apt-get install -y software-properties-common 
          sudo apt-get update 
          sudo add-apt-repository -y ppa:git-core/ppa 
          sudo apt-get update 
          sudo apt-get install -y git
      - uses: actions/checkout@v2
      - name: pull and run docker image
        run: |
          docker pull pataei/petr4:main
          docker run --privileged -w /p4_diff_test -v $(pwd):/p4_diff_test -it pataei/petr4:main /bin/bash
        shell: bash
      - name: stf test petr4 vs p4c
        run: ./.github/scripts/stf-test-petr4-vs-p4c.sh
        shell: bash
      - name: add result of stf test to git repo
        run: |
          git config --local user.email "paris.ataei@gmail.com"
          git config --local user.name  "Github Action Bot GO!"
          git --version
          git status
          git add ci-test/stf-test/*
          git status
          git commit -am "write stf result...see if p4c is working"
          git status
          pwd
          ls -la
          git push origin
