name: push-petr4-docker-img

# Controls when the workflow will run
on:
  # Triggers the workflow after the "" workflow 
  # has completed successfully.
  workflow_run:
    workflows: ["build-petr4"]
    branches: [main]
    types: 
      - completed

jobs:
  build-push-docker-img:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps: 
      - name: checkout main
        uses: actions/checkout@v1
      
      - name: log in to docker hub 
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME}}
          password: ${{ secrets.DOCKER_PASSWORD}}

      - name: extract metadata for docker 
        id: meta 
        uses: docker/metadata-action@v1
        with:
          images: pataei/petr4

      - name: build and push docker img 
        uses: docker/build-push-action@v1
        with:
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.tags }}


